name: emailer
description: Automatically announce and send mails to list of subscribers on every product release 
author: rajan
branding:
  icon: send
  color: red
inputs:
  server_address:
    description: SMTP server address
    required: true
  server_port:
    description: SMTP server port
    required: true
  username:
    description: Authenticate as this user to SMTP server
    required: true
  password:
    description: Authenticate with this password to SMTP server
    required: true
  subject:
    description: Subject of mail message
    required: true
  body:
    description: Body of mail message (might be a filename prefixed with file:// to read from)
    required: true
  to:
    description: Recipients mail addresses (separated with comma)
    required: true
  from:
    description: Full name of mail sender (might be with an email address specified in <>)
    required: true
  content_type:
    description: Content-Type HTTP header (text/html or text/plain)
    required: false
    default: text/plain
  attachments:
    description: Files that will be added to mail message attachments (separated with comma)
    required: false
runs:
  using: node12
  main: main.js
